### ISSUE TITLE
React Native

### ISSUE THREAD

**Issue by artemyarulin** [mfikes/goby#7]
Hi, thank you for your project,

Just wondering - React Native functionality overlaps with goby, what are your thoughts about that?

**Comment by mfikes** [comment]
Indeed. Goby can be summarized as a thin ClojureScript layer over the mutable iOS SDK. I've thought that, to "fix" the mutability issue would involve a lot code to render an iOS UI using pure functions driven by app state, perhaps making use of Om, or being Om-like. Given the likely size of this effort, for now, I just stuck with the simpler, "thin wrapper" approach, in order to get something out the door.

In the meanwhile, Facebook has been chewing on the same problem internally (see some of the older videos by Adam Ernst, describing how they rewrote the Facebook app in a functional way using Objective-C++), and ultimately surfaced the same concepts as React Native. (In fact, the existence of Goby being used in a shipping app was one small example the Facebook React Native team could point to proving that the "crazy" concept of a Hybrid Native/JS app could indeed fly. Of course, they took it _much_ farther.)

So, David Nolen and I have been working on the idea of essentially making Om work with React Native. The first step was putting together [Ambly](https://github.com/omcljs/ambly). And other bits to be sorted through include being able to consume React Native JavaScript modules (CommonJS), which David's been working on (see [here](https://github.com/swannodette/jsx-fun)).

In my mind, Goby is fine—it works—but the future of Om on React Native looks much much more compelling, and is in line with my initial motivations for getting into this business of writing iOS apps in ClojureScript.

If you haven't seen it yet, check out David Nolen's presentation from a few days ago: https://youtu.be/NvF-GZI20L4

**Comment by artemyarulin** [comment]
I've seen this video yesterday - and this was a reason why I decided to create this issue :)

I'm already using ClojureScript in my iOS application, but I've done it in the most easiest way - ClojureScript contains only business logic, while Objective-C responsible for UI and calling appropriate functions in ClojureScript. Ability to update part of application multiple times per day - makes me so happy :)

Looking forward to see Om and React Native together, immutability FTW, it's gonna be really awesome, I promise to test and provide feedback as early as possible. 

Thank you!

**Comment by mfikes** [comment]
@artemyarulin Thanks! Also, the intent is that Ambly be generally useful (outside of the context of React Native). Previously I would use Weasel (and simple-brepl) to establish a REPL into my Goby-based iOS app and have since switched to dog-fooding Ambly. I've updated [Shrimp](https://github.com/mfikes/shrimp) to do the same. If you are ever interested in using Ambly to REPL into the business logic of your current application, I'd be curious if it has sufficient hooks.

**Comment by artemyarulin** [comment]
I have a task on my list to start running unit-test on JSCore, like it is described here [ClojureScript Compiler Tests on iOS](http://blog.fikesfarm.com/posts/2015-03-16-clojurescript-compiler-tests-on-ios.html), so I'll deffinitly start using Ambly in some near feature.

Once again - thank you very much for all this information and projects. I've started using Clojure just a couple of months ago and I haven't been so much in love with programming language in my life :)
